apiVersion: v1
kind: Service
metadata:
  name: app-ms-catalog-service
spec:
  ports: 2
    - port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    name: app-ms-catalog-service
  type: LoadBalancer

