apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-ms-catalog-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app-ms-catalog
    spec:
      containers: 
      - name: app-ms-catalog
        image: soabel/app-ms-catalog:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80      
--
apiVersion: v1
kind: Service
metadata:
  name: app-ms-catalog-service
  labels:
    run: app-ms-catalog-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: app-ms-catalog-service
    run: app-ms-catalog-service
