apiVersion: v1
kind: Service
metadata:
  name: app-ms-catalog-service
  labels:
    run: app-ms-catalog-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: app-ms-catalog-service
    run: app-ms-catalog-service
